require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UdpSocketsController do

  # This should return the minimal set of attributes required to create a valid
  # UdpSocket. As you add validations to UdpSocket, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      port: rand(2**16 - 2**10) + 2**10
    }
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UdpSocketsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all udp_sockets as @udp_sockets" do
      udp_socket = UdpSocket.create! valid_attributes
      get :index, {}, valid_session
      assigns(:udp_sockets).should eq([udp_socket])
    end
  end

  describe "GET show" do
    it "assigns the requested udp_socket as @udp_socket" do
      udp_socket = UdpSocket.create! valid_attributes
      get :show, {:id => udp_socket.to_param}, valid_session
      assigns(:udp_socket).should eq(udp_socket)
    end
  end

  describe "GET new" do
    it "assigns a new udp_socket as @udp_socket" do
      get :new, {}, valid_session
      assigns(:udp_socket).should be_a_new(UdpSocket)
    end
  end

  describe "GET edit" do
    it "assigns the requested udp_socket as @udp_socket" do
      udp_socket = UdpSocket.create! valid_attributes
      get :edit, {:id => udp_socket.to_param}, valid_session
      assigns(:udp_socket).should eq(udp_socket)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UdpSocket" do
        expect {
          post :create, {:udp_socket => valid_attributes}, valid_session
        }.to change(UdpSocket, :count).by(1)
      end

      it "assigns a newly created udp_socket as @udp_socket" do
        post :create, {:udp_socket => valid_attributes}, valid_session
        assigns(:udp_socket).should be_a(UdpSocket)
        assigns(:udp_socket).should be_persisted
      end

      it "redirects to the created udp_socket" do
        post :create, {:udp_socket => valid_attributes}, valid_session
        response.should redirect_to(UdpSocket.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved udp_socket as @udp_socket" do
        # Trigger the behavior that occurs when invalid params are submitted
        UdpSocket.any_instance.stub(:save).and_return(false)
        post :create, {:udp_socket => {}}, valid_session
        assigns(:udp_socket).should be_a_new(UdpSocket)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UdpSocket.any_instance.stub(:save).and_return(false)
        post :create, {:udp_socket => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested udp_socket" do
        udp_socket = UdpSocket.create! valid_attributes
        # Assuming there are no other udp_sockets in the database, this
        # specifies that the UdpSocket created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UdpSocket.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => udp_socket.to_param, :udp_socket => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested udp_socket as @udp_socket" do
        udp_socket = UdpSocket.create! valid_attributes
        put :update, {:id => udp_socket.to_param, :udp_socket => valid_attributes}, valid_session
        assigns(:udp_socket).should eq(udp_socket)
      end

      it "redirects to the udp_socket" do
        udp_socket = UdpSocket.create! valid_attributes
        put :update, {:id => udp_socket.to_param, :udp_socket => valid_attributes}, valid_session
        response.should redirect_to(udp_socket)
      end
    end

    describe "with invalid params" do
      it "assigns the udp_socket as @udp_socket" do
        udp_socket = UdpSocket.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UdpSocket.any_instance.stub(:save).and_return(false)
        put :update, {:id => udp_socket.to_param, :udp_socket => {}}, valid_session
        assigns(:udp_socket).should eq(udp_socket)
      end

      it "re-renders the 'edit' template" do
        udp_socket = UdpSocket.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UdpSocket.any_instance.stub(:save).and_return(false)
        put :update, {:id => udp_socket.to_param, :udp_socket => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested udp_socket" do
      udp_socket = UdpSocket.create! valid_attributes
      expect {
        delete :destroy, {:id => udp_socket.to_param}, valid_session
      }.to change(UdpSocket, :count).by(-1)
    end

    it "redirects to the udp_sockets list" do
      udp_socket = UdpSocket.create! valid_attributes
      delete :destroy, {:id => udp_socket.to_param}, valid_session
      response.should redirect_to(udp_sockets_url)
    end
  end

end
